name: Docker Container
on:
    push:
        branches: [main]
jobs:
    node-docker-container:
        runs-on: ubuntu-latest
        container:
            image: node:20-alpine
        steps:
            - name: Log node and os version
              run: |
                  node -v
                  cat /etc/os-release
            - name: Run docker container
              run: |
                  docker run -d -p 3000:3000
