name: CI-CD

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    build_test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20.x]
                mongodb-version: ['6.0']
                redis-version: [7]
        env:
            NODE_ENV: 'test'
            DB_URL: ${{secrets.DB_URL}}
            COOKIE_SECRET_KEY: ${{secrets.COOKIE_SECRET_KEY}}
            TOKEN_SECRET_KEY: ${{secrets.TOKEN_SECRET_KEY}}
            KAVENEGAR_API_KEY: ${{secrets.KAVENEGAR_API_KEY}}
        steps:
            - uses: actions/checkout@v4

            - name: setup node
              uses: actions/setup-node@v4.0.1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: npm install

            - name: Start MongoDB
              uses: supercharge/mongodb-github-action@1.10.0
              with:
                  mongodb-version: ${{ matrix.mongodb-version }}

            - name: Start Redis
              uses: supercharge/redis-github-action@1.8.0
              with:
                  redis-version: ${{ matrix.redis-version }}

            - name: tests
              run: npm run test
    push_to_Docker_Hub:
        runs-on: ubuntu-latest
        needs: [build_test]

        steps:
            - name: checkout repo
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  context: ./
                  file: ./Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/divar-clone-expressjs:latest

            - name: Run the image in a container
              uses: addnab/docker-run-action@v3
              with:
                  image: ${{ secrets.DOCKERHUB_USERNAME }}/divar-clone-expressjs:latest
                  run: |
                      echo "runing the docker image"
                      echo "Testing the nodejs  app endpoints"
                      echo ${{ steps.docker_build.outputs.digest }}
